<?php

namespace MyFirstBundle\Repository;

/**
 * private_messageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class private_messageRepository extends \Doctrine\ORM\EntityRepository
{
}
